---
- name: Install Java package (Ubuntu/Debian)
  apt:
    name: "{{ java.apt_package }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags:
    - java
    - java_installation

- name: Install Java package (CentOS/RHEL)
  yum:
    name: "{{ java.yum_package }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  tags:
    - java
    - java_installation
